// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module axi_vga_reg_top (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [5:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        output axi_vga_reg_pkg::axi_vga__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[5:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic control;
        logic clk_div;
        logic hori_visible_size;
        logic hori_front_porch_size;
        logic hori_sync_size;
        logic hori_back_porch_size;
        logic vert_visible_size;
        logic vert_front_porch_size;
        logic vert_sync_size;
        logic vert_back_porch_size;
        logic start_addr_low;
        logic start_addr_high;
        logic frame_size;
        logic burst_len;
        logic burst_split_len;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [5:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.control = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.clk_div = cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.hori_visible_size = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.hori_front_porch_size = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.hori_sync_size = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.hori_back_porch_size = cpuif_req_masked & (cpuif_addr == 6'h14);
        decoded_reg_strb.vert_visible_size = cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.vert_front_porch_size = cpuif_req_masked & (cpuif_addr == 6'h1c);
        decoded_reg_strb.vert_sync_size = cpuif_req_masked & (cpuif_addr == 6'h20);
        decoded_reg_strb.vert_back_porch_size = cpuif_req_masked & (cpuif_addr == 6'h24);
        decoded_reg_strb.start_addr_low = cpuif_req_masked & (cpuif_addr == 6'h28);
        decoded_reg_strb.start_addr_high = cpuif_req_masked & (cpuif_addr == 6'h2c);
        decoded_reg_strb.frame_size = cpuif_req_masked & (cpuif_addr == 6'h30);
        decoded_reg_strb.burst_len = cpuif_req_masked & (cpuif_addr == 6'h34);
        decoded_reg_strb.burst_split_len = cpuif_req_masked & (cpuif_addr == 6'h38);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } enable;
            struct {
                logic next;
                logic load_next;
            } hsync_pol;
            struct {
                logic next;
                logic load_next;
            } vsync_pol;
        } control;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } clk_div;
        } clk_div;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } hori_visible_size;
        } hori_visible_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } hori_front_porch_size;
        } hori_front_porch_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } hori_sync_size;
        } hori_sync_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } hori_back_porch_size;
        } hori_back_porch_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } vert_visible_size;
        } vert_visible_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } vert_front_porch_size;
        } vert_front_porch_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } vert_sync_size;
        } vert_sync_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } vert_back_porch_size;
        } vert_back_porch_size;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } start_addr_low;
        } start_addr_low;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } start_addr_high;
        } start_addr_high;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } frame_size;
        } frame_size;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } burst_len;
        } burst_len;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } burst_len;
        } burst_split_len;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } enable;
            struct {
                logic value;
            } hsync_pol;
            struct {
                logic value;
            } vsync_pol;
        } control;
        struct {
            struct {
                logic [7:0] value;
            } clk_div;
        } clk_div;
        struct {
            struct {
                logic [31:0] value;
            } hori_visible_size;
        } hori_visible_size;
        struct {
            struct {
                logic [31:0] value;
            } hori_front_porch_size;
        } hori_front_porch_size;
        struct {
            struct {
                logic [31:0] value;
            } hori_sync_size;
        } hori_sync_size;
        struct {
            struct {
                logic [31:0] value;
            } hori_back_porch_size;
        } hori_back_porch_size;
        struct {
            struct {
                logic [31:0] value;
            } vert_visible_size;
        } vert_visible_size;
        struct {
            struct {
                logic [31:0] value;
            } vert_front_porch_size;
        } vert_front_porch_size;
        struct {
            struct {
                logic [31:0] value;
            } vert_sync_size;
        } vert_sync_size;
        struct {
            struct {
                logic [31:0] value;
            } vert_back_porch_size;
        } vert_back_porch_size;
        struct {
            struct {
                logic [31:0] value;
            } start_addr_low;
        } start_addr_low;
        struct {
            struct {
                logic [31:0] value;
            } start_addr_high;
        } start_addr_high;
        struct {
            struct {
                logic [31:0] value;
            } frame_size;
        } frame_size;
        struct {
            struct {
                logic [7:0] value;
            } burst_len;
        } burst_len;
        struct {
            struct {
                logic [7:0] value;
            } burst_len;
        } burst_split_len;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: axi_vga.control.enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.control.enable.next = next_c;
        field_combo.control.enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.enable.value <= 1'h0;
        end else begin
            if(field_combo.control.enable.load_next) begin
                field_storage.control.enable.value <= field_combo.control.enable.next;
            end
        end
    end
    assign hwif_out.control.enable.value = field_storage.control.enable.value;
    // Field: axi_vga.control.hsync_pol
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.hsync_pol.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.hsync_pol.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.control.hsync_pol.next = next_c;
        field_combo.control.hsync_pol.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.hsync_pol.value <= 1'h1;
        end else begin
            if(field_combo.control.hsync_pol.load_next) begin
                field_storage.control.hsync_pol.value <= field_combo.control.hsync_pol.next;
            end
        end
    end
    assign hwif_out.control.hsync_pol.value = field_storage.control.hsync_pol.value;
    // Field: axi_vga.control.vsync_pol
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.vsync_pol.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.vsync_pol.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.control.vsync_pol.next = next_c;
        field_combo.control.vsync_pol.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.vsync_pol.value <= 1'h1;
        end else begin
            if(field_combo.control.vsync_pol.load_next) begin
                field_storage.control.vsync_pol.value <= field_combo.control.vsync_pol.next;
            end
        end
    end
    assign hwif_out.control.vsync_pol.value = field_storage.control.vsync_pol.value;
    // Field: axi_vga.clk_div.clk_div
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clk_div.clk_div.value;
        load_next_c = '0;
        if(decoded_reg_strb.clk_div && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clk_div.clk_div.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.clk_div.clk_div.next = next_c;
        field_combo.clk_div.clk_div.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.clk_div.clk_div.value <= 8'h1;
        end else begin
            if(field_combo.clk_div.clk_div.load_next) begin
                field_storage.clk_div.clk_div.value <= field_combo.clk_div.clk_div.next;
            end
        end
    end
    assign hwif_out.clk_div.clk_div.value = field_storage.clk_div.clk_div.value;
    // Field: axi_vga.hori_visible_size.hori_visible_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hori_visible_size.hori_visible_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hori_visible_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hori_visible_size.hori_visible_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hori_visible_size.hori_visible_size.next = next_c;
        field_combo.hori_visible_size.hori_visible_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.hori_visible_size.hori_visible_size.value <= 32'h1;
        end else begin
            if(field_combo.hori_visible_size.hori_visible_size.load_next) begin
                field_storage.hori_visible_size.hori_visible_size.value <= field_combo.hori_visible_size.hori_visible_size.next;
            end
        end
    end
    assign hwif_out.hori_visible_size.hori_visible_size.value = field_storage.hori_visible_size.hori_visible_size.value;
    // Field: axi_vga.hori_front_porch_size.hori_front_porch_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hori_front_porch_size.hori_front_porch_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hori_front_porch_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hori_front_porch_size.hori_front_porch_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hori_front_porch_size.hori_front_porch_size.next = next_c;
        field_combo.hori_front_porch_size.hori_front_porch_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.hori_front_porch_size.hori_front_porch_size.value <= 32'h1;
        end else begin
            if(field_combo.hori_front_porch_size.hori_front_porch_size.load_next) begin
                field_storage.hori_front_porch_size.hori_front_porch_size.value <= field_combo.hori_front_porch_size.hori_front_porch_size.next;
            end
        end
    end
    assign hwif_out.hori_front_porch_size.hori_front_porch_size.value = field_storage.hori_front_porch_size.hori_front_porch_size.value;
    // Field: axi_vga.hori_sync_size.hori_sync_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hori_sync_size.hori_sync_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hori_sync_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hori_sync_size.hori_sync_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hori_sync_size.hori_sync_size.next = next_c;
        field_combo.hori_sync_size.hori_sync_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.hori_sync_size.hori_sync_size.value <= 32'h1;
        end else begin
            if(field_combo.hori_sync_size.hori_sync_size.load_next) begin
                field_storage.hori_sync_size.hori_sync_size.value <= field_combo.hori_sync_size.hori_sync_size.next;
            end
        end
    end
    assign hwif_out.hori_sync_size.hori_sync_size.value = field_storage.hori_sync_size.hori_sync_size.value;
    // Field: axi_vga.hori_back_porch_size.hori_back_porch_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hori_back_porch_size.hori_back_porch_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hori_back_porch_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hori_back_porch_size.hori_back_porch_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hori_back_porch_size.hori_back_porch_size.next = next_c;
        field_combo.hori_back_porch_size.hori_back_porch_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.hori_back_porch_size.hori_back_porch_size.value <= 32'h1;
        end else begin
            if(field_combo.hori_back_porch_size.hori_back_porch_size.load_next) begin
                field_storage.hori_back_porch_size.hori_back_porch_size.value <= field_combo.hori_back_porch_size.hori_back_porch_size.next;
            end
        end
    end
    assign hwif_out.hori_back_porch_size.hori_back_porch_size.value = field_storage.hori_back_porch_size.hori_back_porch_size.value;
    // Field: axi_vga.vert_visible_size.vert_visible_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.vert_visible_size.vert_visible_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.vert_visible_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.vert_visible_size.vert_visible_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.vert_visible_size.vert_visible_size.next = next_c;
        field_combo.vert_visible_size.vert_visible_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.vert_visible_size.vert_visible_size.value <= 32'h1;
        end else begin
            if(field_combo.vert_visible_size.vert_visible_size.load_next) begin
                field_storage.vert_visible_size.vert_visible_size.value <= field_combo.vert_visible_size.vert_visible_size.next;
            end
        end
    end
    assign hwif_out.vert_visible_size.vert_visible_size.value = field_storage.vert_visible_size.vert_visible_size.value;
    // Field: axi_vga.vert_front_porch_size.vert_front_porch_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.vert_front_porch_size.vert_front_porch_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.vert_front_porch_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.vert_front_porch_size.vert_front_porch_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.vert_front_porch_size.vert_front_porch_size.next = next_c;
        field_combo.vert_front_porch_size.vert_front_porch_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.vert_front_porch_size.vert_front_porch_size.value <= 32'h1;
        end else begin
            if(field_combo.vert_front_porch_size.vert_front_porch_size.load_next) begin
                field_storage.vert_front_porch_size.vert_front_porch_size.value <= field_combo.vert_front_porch_size.vert_front_porch_size.next;
            end
        end
    end
    assign hwif_out.vert_front_porch_size.vert_front_porch_size.value = field_storage.vert_front_porch_size.vert_front_porch_size.value;
    // Field: axi_vga.vert_sync_size.vert_sync_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.vert_sync_size.vert_sync_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.vert_sync_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.vert_sync_size.vert_sync_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.vert_sync_size.vert_sync_size.next = next_c;
        field_combo.vert_sync_size.vert_sync_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.vert_sync_size.vert_sync_size.value <= 32'h1;
        end else begin
            if(field_combo.vert_sync_size.vert_sync_size.load_next) begin
                field_storage.vert_sync_size.vert_sync_size.value <= field_combo.vert_sync_size.vert_sync_size.next;
            end
        end
    end
    assign hwif_out.vert_sync_size.vert_sync_size.value = field_storage.vert_sync_size.vert_sync_size.value;
    // Field: axi_vga.vert_back_porch_size.vert_back_porch_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.vert_back_porch_size.vert_back_porch_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.vert_back_porch_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.vert_back_porch_size.vert_back_porch_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.vert_back_porch_size.vert_back_porch_size.next = next_c;
        field_combo.vert_back_porch_size.vert_back_porch_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.vert_back_porch_size.vert_back_porch_size.value <= 32'h1;
        end else begin
            if(field_combo.vert_back_porch_size.vert_back_porch_size.load_next) begin
                field_storage.vert_back_porch_size.vert_back_porch_size.value <= field_combo.vert_back_porch_size.vert_back_porch_size.next;
            end
        end
    end
    assign hwif_out.vert_back_porch_size.vert_back_porch_size.value = field_storage.vert_back_porch_size.vert_back_porch_size.value;
    // Field: axi_vga.start_addr_low.start_addr_low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.start_addr_low.start_addr_low.value;
        load_next_c = '0;
        if(decoded_reg_strb.start_addr_low && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.start_addr_low.start_addr_low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.start_addr_low.start_addr_low.next = next_c;
        field_combo.start_addr_low.start_addr_low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.start_addr_low.start_addr_low.value <= 32'h0;
        end else begin
            if(field_combo.start_addr_low.start_addr_low.load_next) begin
                field_storage.start_addr_low.start_addr_low.value <= field_combo.start_addr_low.start_addr_low.next;
            end
        end
    end
    assign hwif_out.start_addr_low.start_addr_low.value = field_storage.start_addr_low.start_addr_low.value;
    // Field: axi_vga.start_addr_high.start_addr_high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.start_addr_high.start_addr_high.value;
        load_next_c = '0;
        if(decoded_reg_strb.start_addr_high && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.start_addr_high.start_addr_high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.start_addr_high.start_addr_high.next = next_c;
        field_combo.start_addr_high.start_addr_high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.start_addr_high.start_addr_high.value <= 32'h0;
        end else begin
            if(field_combo.start_addr_high.start_addr_high.load_next) begin
                field_storage.start_addr_high.start_addr_high.value <= field_combo.start_addr_high.start_addr_high.next;
            end
        end
    end
    assign hwif_out.start_addr_high.start_addr_high.value = field_storage.start_addr_high.start_addr_high.value;
    // Field: axi_vga.frame_size.frame_size
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.frame_size.frame_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.frame_size && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.frame_size.frame_size.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.frame_size.frame_size.next = next_c;
        field_combo.frame_size.frame_size.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.frame_size.frame_size.value <= 32'h0;
        end else begin
            if(field_combo.frame_size.frame_size.load_next) begin
                field_storage.frame_size.frame_size.value <= field_combo.frame_size.frame_size.next;
            end
        end
    end
    assign hwif_out.frame_size.frame_size.value = field_storage.frame_size.frame_size.value;
    // Field: axi_vga.burst_len.burst_len
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.burst_len.burst_len.value;
        load_next_c = '0;
        if(decoded_reg_strb.burst_len && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.burst_len.burst_len.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.burst_len.burst_len.next = next_c;
        field_combo.burst_len.burst_len.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.burst_len.burst_len.value <= 8'h0;
        end else begin
            if(field_combo.burst_len.burst_len.load_next) begin
                field_storage.burst_len.burst_len.value <= field_combo.burst_len.burst_len.next;
            end
        end
    end
    assign hwif_out.burst_len.burst_len.value = field_storage.burst_len.burst_len.value;
    // Field: axi_vga.burst_split_len.burst_len
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.burst_split_len.burst_len.value;
        load_next_c = '0;
        if(decoded_reg_strb.burst_split_len && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.burst_split_len.burst_len.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.burst_split_len.burst_len.next = next_c;
        field_combo.burst_split_len.burst_len.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.burst_split_len.burst_len.value <= 8'h0;
        end else begin
            if(field_combo.burst_split_len.burst_len.load_next) begin
                field_storage.burst_split_len.burst_len.value <= field_combo.burst_split_len.burst_len.next;
            end
        end
    end
    assign hwif_out.burst_split_len.burst_len.value = field_storage.burst_split_len.burst_len.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [5:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 6'h0) begin
            readback_data_var[0] = field_storage.control.enable.value;
            readback_data_var[1] = field_storage.control.hsync_pol.value;
            readback_data_var[2] = field_storage.control.vsync_pol.value;
        end
        if(rd_mux_addr == 6'h4) begin
            readback_data_var[7:0] = field_storage.clk_div.clk_div.value;
        end
        if(rd_mux_addr == 6'h8) begin
            readback_data_var[31:0] = field_storage.hori_visible_size.hori_visible_size.value;
        end
        if(rd_mux_addr == 6'hc) begin
            readback_data_var[31:0] = field_storage.hori_front_porch_size.hori_front_porch_size.value;
        end
        if(rd_mux_addr == 6'h10) begin
            readback_data_var[31:0] = field_storage.hori_sync_size.hori_sync_size.value;
        end
        if(rd_mux_addr == 6'h14) begin
            readback_data_var[31:0] = field_storage.hori_back_porch_size.hori_back_porch_size.value;
        end
        if(rd_mux_addr == 6'h18) begin
            readback_data_var[31:0] = field_storage.vert_visible_size.vert_visible_size.value;
        end
        if(rd_mux_addr == 6'h1c) begin
            readback_data_var[31:0] = field_storage.vert_front_porch_size.vert_front_porch_size.value;
        end
        if(rd_mux_addr == 6'h20) begin
            readback_data_var[31:0] = field_storage.vert_sync_size.vert_sync_size.value;
        end
        if(rd_mux_addr == 6'h24) begin
            readback_data_var[31:0] = field_storage.vert_back_porch_size.vert_back_porch_size.value;
        end
        if(rd_mux_addr == 6'h28) begin
            readback_data_var[31:0] = field_storage.start_addr_low.start_addr_low.value;
        end
        if(rd_mux_addr == 6'h2c) begin
            readback_data_var[31:0] = field_storage.start_addr_high.start_addr_high.value;
        end
        if(rd_mux_addr == 6'h30) begin
            readback_data_var[31:0] = field_storage.frame_size.frame_size.value;
        end
        if(rd_mux_addr == 6'h34) begin
            readback_data_var[7:0] = field_storage.burst_len.burst_len.value;
        end
        if(rd_mux_addr == 6'h38) begin
            readback_data_var[7:0] = field_storage.burst_split_len.burst_len.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
