// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package axi_vga_reg_pkg;

    localparam AXI_VGA_REG_TOP_DATA_WIDTH = 32;
    localparam AXI_VGA_REG_TOP_MIN_ADDR_WIDTH = 6;
    localparam AXI_VGA_REG_TOP_SIZE = 'h3c;

    typedef struct {
        logic value;
    } axi_vga__control__enable__out_t;

    typedef struct {
        logic value;
    } axi_vga__control__hsync_pol__out_t;

    typedef struct {
        logic value;
    } axi_vga__control__vsync_pol__out_t;

    typedef struct {
        axi_vga__control__enable__out_t enable;
        axi_vga__control__hsync_pol__out_t hsync_pol;
        axi_vga__control__vsync_pol__out_t vsync_pol;
    } axi_vga__control__out_t;

    typedef struct {
        logic [7:0] value;
    } axi_vga__clk_div__clk_div__out_t;

    typedef struct {
        axi_vga__clk_div__clk_div__out_t clk_div;
    } axi_vga__clk_div__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__hori_visible_size__hori_visible_size__out_t;

    typedef struct {
        axi_vga__hori_visible_size__hori_visible_size__out_t hori_visible_size;
    } axi_vga__hori_visible_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__hori_front_porch_size__hori_front_porch_size__out_t;

    typedef struct {
        axi_vga__hori_front_porch_size__hori_front_porch_size__out_t hori_front_porch_size;
    } axi_vga__hori_front_porch_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__hori_sync_size__hori_sync_size__out_t;

    typedef struct {
        axi_vga__hori_sync_size__hori_sync_size__out_t hori_sync_size;
    } axi_vga__hori_sync_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__hori_back_porch_size__hori_back_porch_size__out_t;

    typedef struct {
        axi_vga__hori_back_porch_size__hori_back_porch_size__out_t hori_back_porch_size;
    } axi_vga__hori_back_porch_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__vert_visible_size__vert_visible_size__out_t;

    typedef struct {
        axi_vga__vert_visible_size__vert_visible_size__out_t vert_visible_size;
    } axi_vga__vert_visible_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__vert_front_porch_size__vert_front_porch_size__out_t;

    typedef struct {
        axi_vga__vert_front_porch_size__vert_front_porch_size__out_t vert_front_porch_size;
    } axi_vga__vert_front_porch_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__vert_sync_size__vert_sync_size__out_t;

    typedef struct {
        axi_vga__vert_sync_size__vert_sync_size__out_t vert_sync_size;
    } axi_vga__vert_sync_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__vert_back_porch_size__vert_back_porch_size__out_t;

    typedef struct {
        axi_vga__vert_back_porch_size__vert_back_porch_size__out_t vert_back_porch_size;
    } axi_vga__vert_back_porch_size__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__start_addr_low__start_addr_low__out_t;

    typedef struct {
        axi_vga__start_addr_low__start_addr_low__out_t start_addr_low;
    } axi_vga__start_addr_low__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__start_addr_high__start_addr_high__out_t;

    typedef struct {
        axi_vga__start_addr_high__start_addr_high__out_t start_addr_high;
    } axi_vga__start_addr_high__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_vga__frame_size__frame_size__out_t;

    typedef struct {
        axi_vga__frame_size__frame_size__out_t frame_size;
    } axi_vga__frame_size__out_t;

    typedef struct {
        logic [7:0] value;
    } axi_vga__burst_len__burst_len__out_t;

    typedef struct {
        axi_vga__burst_len__burst_len__out_t burst_len;
    } axi_vga__burst_len__out_t;

    typedef struct {
        logic [7:0] value;
    } axi_vga__burst_split_len__burst_len__out_t;

    typedef struct {
        axi_vga__burst_split_len__burst_len__out_t burst_len;
    } axi_vga__burst_split_len__out_t;

    typedef struct {
        axi_vga__control__out_t control;
        axi_vga__clk_div__out_t clk_div;
        axi_vga__hori_visible_size__out_t hori_visible_size;
        axi_vga__hori_front_porch_size__out_t hori_front_porch_size;
        axi_vga__hori_sync_size__out_t hori_sync_size;
        axi_vga__hori_back_porch_size__out_t hori_back_porch_size;
        axi_vga__vert_visible_size__out_t vert_visible_size;
        axi_vga__vert_front_porch_size__out_t vert_front_porch_size;
        axi_vga__vert_sync_size__out_t vert_sync_size;
        axi_vga__vert_back_porch_size__out_t vert_back_porch_size;
        axi_vga__start_addr_low__out_t start_addr_low;
        axi_vga__start_addr_high__out_t start_addr_high;
        axi_vga__frame_size__out_t frame_size;
        axi_vga__burst_len__out_t burst_len;
        axi_vga__burst_split_len__out_t burst_split_len;
    } axi_vga__out_t;
endpackage
